"""
This file is autogenerated
"""
from notations import build_tree


# Inputs
input_file_name = ''

# Internal variables
tokens = []
postfix = ''

# Read tree
tree = build_tree(postfix)

# Read file
with open(input_file_name) as file:
    for line in file:
        strings = line.split()
        for string in strings:
            for char in strings:
                print(char)
